routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
	if(Auth::check()) {
		return redirect('home');
	} else {
		return view('welcome');
	}
});

Auth::routes();

Route::get('/testemail', function() {
	$message = "Hello World!!!!";
    Mail::send('welcome', ['title' => 'Test Email', 'message' => $message], function($message) {
        $message->to('donny.p.perdana@gmail.com')->subject('Testing mails');
    });
});

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/profile', 'HomeController@profile')->name('profile');
// Route::get('/book', 'HomeController@book')->name('book');

// System Configuration > Stores
Route::resource('stores', 'StoreController')->only('index', 'create', 'store', 'edit');
Route::post('stores/{store}/update', 'StoreController@update')->name('stores.update');
Route::post('stores/{store}/delete', 'StoreController@delete')->name('stores.delete');

// System Configuration > Categories
Route::resource('categories', 'CategoryController')->only('index', 'create', 'store', 'edit');
Route::post('category/{category}/update', 'CategoryController@update')->name('categories.update');
Route::post('category/{category}/delete', 'CategoryController@delete')->name('categories.delete');

// System Configuration > Item Status
Route::resource('itemstatuses', 'ItemStatusController')->only('index', 'create', 'store', 'edit');
Route::post('itemstatus/{itemstatus}/update', 'ItemStatusController@update')->name('itemstatuses.update');
Route::post('itemstatus/{itemstatus}/delete', 'ItemStatusController@delete')->name('itemstatuses.delete');

// System Configuration > Inventory Status
Route::resource('inventorystatuses', 'InventoryStatusController')->only('index', 'create', 'store', 'edit');
Route::post('inventorystatus/{inventorystatus}/update', 'InventoryStatusController@update')->name('inventorystatuses.update');
Route::post('inventorystatus/{inventorystatus}/delete', 'InventoryStatusController@delete')->name('inventorystatuses.delete');

// System Configuration > Allocation
Route::resource('allocations', 'AllocationController')->only('index', 'create', 'store', 'edit');
Route::post('allocation/{allocation}/update', 'AllocationController@update')->name('allocations.update');
Route::post('allocation/{allocation}/delete', 'AllocationController@delete')->name('allocations.delete');

// System Configuration > Sales Status
Route::resource('salesstatuses', 'SalesStatusController')->only('index', 'create', 'store', 'edit');
Route::post('salesstatus/{salesstatus}/update', 'SalesStatusController@update')->name('salesstatuses.update');
Route::post('salesstatus/{salesstatus}/delete', 'SalesStatusController@delete')->name('salesstatuses.delete');

// System Configuration > Buyback Status
Route::resource('buybackstatuses', 'BuybackStatusController')->only('index', 'create', 'store', 'edit');
Route::post('buybackstatus/{buybackstatus}/update', 'BuybackStatusController@update')->name('buybackstatuses.update');
Route::post('buybackstatus/{buybackstatus}/delete', 'BuybackStatusController@delete')->name('buybackstatuses.delete');

// System Configuration > Users
Route::resource('users', 'UserController')->only('index', 'create', 'store', 'edit');
Route::get('users/{user}/changepassword', 'UserController@changepassword')->name('users.changepassword');
Route::post('users/{user}/update', 'UserController@update')->name('users.update');
Route::post('users/{user}/delete', 'UserController@delete')->name('users.delete');
Route::post('users/{user}/updatepassword', 'UserController@updatepassword')->name('users.updatepassword');

// System Configuration > Roles
Route::resource('roles', 'RoleController')->only('index', 'create', 'store', 'edit');
Route::post('roles/{role}/update', 'RoleController@update')->name('roles.update');
Route::post('roles/{role}/delete', 'RoleController@delete')->name('roles.delete');

// Book (Items)
Route::resource('items', 'ItemController')->only('index', 'create', 'store', 'edit');
Route::get('items/applyfilter', 'ItemController@applyfilter')->name('items.applyfilter');
Route::get('items/clearfilter', 'ItemController@clearfilter')->name('items.clearfilter');
Route::get('items/applysort', 'ItemController@applysort')->name('items.applysort');
Route::post('item/{item}/update', 'ItemController@update')->name('items.update');
Route::post('item/{item}/delete', 'ItemController@delete')->name('items.delete');
Route::get('items/bulkupload', 'ItemController@bulkupload')->name('items.bulkupload');
Route::get('items/downloadcsvtemplate', 'ItemController@downloadCsvTemplate')->name('items.downloadcsvtemplate');
Route::post('items/importcsv', 'ItemController@importcsv')->name('items.importcsv');
Route::post('items/massaction', 'ItemController@massaction')->name('items.massaction');

Route::get('employee/items/index', 'ItemController@employeeItemIndex')->name('items.employee.index');
Route::get('employee/items/create', 'ItemController@employeeItemCreate')->name('items.employee.create');
Route::post('employee/items/store', 'ItemController@employeeItemStore')->name('items.employee.store');
Route::post('employee/items/find', 'ItemController@employeeItemFind')->name('items.employee.find');
Route::get('employee/sales/entry', 'ItemController@employeeSalesEntry')->name('sales.employee.entry');
Route::get('employee/sales/form/{itemId}', 'ItemController@employeeSalesForm')->name('sales.employee.form');
Route::post('employee/sales/form/save', 'ItemController@employeeSalesFormSave')->name('sales.employee.form.save');

// Dashboard
Route::resource('dashboard', 'DashboardController')->only('index');

// Sales for Employee

Route::post('/profile/update', 'UserController@profileUpdate')->name('profile.update');

app/Http/Livewire/InventorystatusesTable.php
<?php

namespace App\Http\Livewire;

use Livewire\Component;
use Livewire\WithPagination;

class InventorystatusesTable extends Component
{
    use WithPagination;	

    const INITIAL_SORT_FIELD = 'code';

    public $perPage = 10;
    public $sortField = self::INITIAL_SORT_FIELD;
    public $sortAsc = true;
    public $search = '';

    public function sortBy($field)
    {
        if ($this->sortField === $field) {
            $this->sortAsc = ! $this->sortAsc;
        } else {
            $this->sortAsc = true;
        }

        $this->sortField = $field;
    }

    public function render()
    {
        return view('livewire.inventorystatuses-table', [
            'inventorystatuses' => \App\InventoryStatus::search($this->search)
                ->orderBy($this->sortField, $this->sortAsc ? 'asc' : 'desc')
                ->paginate($this->perPage),
        ]);
    }
}

resources/views/inventorystatuses/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">

			<div class="content-header">
				<div class="container-fluid">
					<div class="row mb-2">
						<div class="col-sm-6">
							<h1 class="m-0 text-dark">{{ __("New Inventory Status") }}</h1>
						</div><!-- /.col -->
						<div class="col-sm-6">
							<ol class="breadcrumb float-sm-right">
								<li class="breadcrumb-item"><a href="/">{{ __("Home") }}</a></li>
								<li class="breadcrumb-item"><a href="{{ route("inventorystatuses.index") }}">{{ __("Inventory Status") }}</a></li>
								<li class="breadcrumb-item active">{{ __("New Inventory Status") }}</li>
							</ol>
						</div><!-- /.col -->
					</div><!-- /.row -->
				</div><!-- /.container-fluid -->
			</div>

			<div class="content">
				<div class="container-fluid">
					<div class="row">
						<div class="col-12">
							<div class="table-responsive">
								<div class="card">
									<div class="card-body">
										<form method="POST" action="{{ route('inventorystatuses.store') }}">
											<div class="form-group">
												@csrf
												<label for="inventorystatus_code">Inventory Status Code</label>
												<input type="text" class="form-control" name="inventorystatus_code" />
											</div>
											<div class="form-group">
												<label for="inventorystatus_description">Inventory Status Description</label>
												<textarea class="form-control" name="inventorystatus_description" rows="3"></textarea>
											</div>
			
											<div class="float-right">
												<a class="btn btn-secondary" href="{{ url()->previous() }}" role="button">{{ __("Back") }}</a>
												<button type="submit" class="btn btn-primary">{{ __("Save") }}</button>
											</div>
										</form>
									</div>
								</div>
							</div>
						</div>
					</div>
					<!-- /.row -->
				</div><!-- /.container-fluid -->
			</div>

        </div>
    </div>
</div>
@endsection

resources/views/inventorystatuses/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">

            <div class="content-header">
                <div class="container-fluid">
                    <div class="row mb-2">
                        <div class="col-sm-6">
                            <h1 class="m-0 text-dark">{{ __("Edit Inventory Status") }}</h1>
                        </div><!-- /.col -->
                        <div class="col-sm-6">
                            <ol class="breadcrumb float-sm-right">
                                <li class="breadcrumb-item"><a href="/">{{ __("Home") }}</a></li>
                                <li class="breadcrumb-item"><a href="{{ route("inventorystatuses.index") }}">{{ __("Inventory Status") }}</a></li>
                                <li class="breadcrumb-item active">{{ __("Edit Inventory Status") }}</li>
                            </ol>
                        </div><!-- /.col -->
                    </div><!-- /.row -->
                </div><!-- /.container-fluid -->
            </div>

            <div class="content">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-12">
                            <div class="table-responsive">
                                <div class="card">
                                    <div class="card-body">
                                        <form method="post" action="{{ route('inventorystatuses.update', $inventorystatus->id) }}">
                                            <div class="form-group">
                                                @csrf
                                                <label for="inventorystatuses_code">Inventory Status Code</label>
                                                <input type="text" class="form-control" name="inventorystatuses_code" value="{{ $inventorystatus->code }}" />
                                            </div>
                                            <div class="form-group">
                                                <label for="inventorystatuses_description">Inventory Status Description</label>
                                                <textarea class="form-control" name="inventorystatuses_description" rows="3">{{ $inventorystatus->description }}</textarea>
                                            </div>
            
                                            <div class="float-right">
                                                <a class="btn btn-secondary" href="{{ url()->previous() }}" role="button">{{ __("Back") }}</a>
                                                <button type="submit" class="btn btn-primary">{{ __("Save") }}</button>
                                            </div>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!-- /.row -->
                </div><!-- /.container-fluid -->
            </div>

        </div>
    </div>
</div>
@endsection

resources/views/inventorystatuses/index.blade.php
@extends('layouts.admin')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">

            <div class="content-header">
                <div class="container-fluid">
                    <div class="row mb-2">
                        <div class="col-sm-6">
                            <h1 class="m-0 text-dark">{{ __("Inventory Status") }}</h1>
                        </div><!-- /.col -->
                        <div class="col-sm-6">
                            <ol class="breadcrumb float-sm-right">
                                <li class="breadcrumb-item"><a href="/">{{ __("Home") }}</a></li>
                                <li class="breadcrumb-item active">{{ __("Inventory Status") }}</li>
                            </ol>
                        </div><!-- /.col -->
                    </div><!-- /.row -->
                </div><!-- /.container-fluid -->
            </div>

            <div class="content">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-12">
                            <p class="text-muted">{{ __("This is predefined options by system. It can't be changed.") }}</p>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-12">
                            <div class="table-responsive">
                                <div class="card">
                                    <div class="card-body">
                                        @livewire('inventorystatuses-table')
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!-- /.row -->
                </div><!-- /.container-fluid -->
            </div>

        </div>
    </div>
</div>
@endsection