routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
	if(Auth::check()) {
		return redirect('home');
	} else {
		return view('welcome');
	}
});

Auth::routes();

Route::get('/testemail', function() {
	$message = "Hello World!!!!";
    Mail::send('welcome', ['title' => 'Test Email', 'message' => $message], function($message) {
        $message->to('donny.p.perdana@gmail.com')->subject('Testing mails');
    });
});

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/profile', 'HomeController@profile')->name('profile');
// Route::get('/book', 'HomeController@book')->name('book');

// System Configuration > Stores
Route::resource('stores', 'StoreController')->only('index', 'create', 'store', 'edit');
Route::post('stores/{store}/update', 'StoreController@update')->name('stores.update');
Route::post('stores/{store}/delete', 'StoreController@delete')->name('stores.delete');

// System Configuration > Categories
Route::resource('categories', 'CategoryController')->only('index', 'create', 'store', 'edit');
Route::post('category/{category}/update', 'CategoryController@update')->name('categories.update');
Route::post('category/{category}/delete', 'CategoryController@delete')->name('categories.delete');

// System Configuration > Item Status
Route::resource('itemstatuses', 'ItemStatusController')->only('index', 'create', 'store', 'edit');
Route::post('itemstatus/{itemstatus}/update', 'ItemStatusController@update')->name('itemstatuses.update');
Route::post('itemstatus/{itemstatus}/delete', 'ItemStatusController@delete')->name('itemstatuses.delete');

// System Configuration > Inventory Status
Route::resource('inventorystatuses', 'InventoryStatusController')->only('index', 'create', 'store', 'edit');
Route::post('inventorystatus/{inventorystatus}/update', 'InventoryStatusController@update')->name('inventorystatuses.update');
Route::post('inventorystatus/{inventorystatus}/delete', 'InventoryStatusController@delete')->name('inventorystatuses.delete');

// System Configuration > Allocation
Route::resource('allocations', 'AllocationController')->only('index', 'create', 'store', 'edit');
Route::post('allocation/{allocation}/update', 'AllocationController@update')->name('allocations.update');
Route::post('allocation/{allocation}/delete', 'AllocationController@delete')->name('allocations.delete');

// System Configuration > Sales Status
Route::resource('salesstatuses', 'SalesStatusController')->only('index', 'create', 'store', 'edit');
Route::post('salesstatus/{salesstatus}/update', 'SalesStatusController@update')->name('salesstatuses.update');
Route::post('salesstatus/{salesstatus}/delete', 'SalesStatusController@delete')->name('salesstatuses.delete');

// System Configuration > Buyback Status
Route::resource('buybackstatuses', 'BuybackStatusController')->only('index', 'create', 'store', 'edit');
Route::post('buybackstatus/{buybackstatus}/update', 'BuybackStatusController@update')->name('buybackstatuses.update');
Route::post('buybackstatus/{buybackstatus}/delete', 'BuybackStatusController@delete')->name('buybackstatuses.delete');

// System Configuration > Users
Route::resource('users', 'UserController')->only('index', 'create', 'store', 'edit');
Route::get('users/{user}/changepassword', 'UserController@changepassword')->name('users.changepassword');
Route::post('users/{user}/update', 'UserController@update')->name('users.update');
Route::post('users/{user}/delete', 'UserController@delete')->name('users.delete');
Route::post('users/{user}/updatepassword', 'UserController@updatepassword')->name('users.updatepassword');

// System Configuration > Roles
Route::resource('roles', 'RoleController')->only('index', 'create', 'store', 'edit');
Route::post('roles/{role}/update', 'RoleController@update')->name('roles.update');
Route::post('roles/{role}/delete', 'RoleController@delete')->name('roles.delete');

// Book (Items)
Route::resource('items', 'ItemController')->only('index', 'create', 'store', 'edit');
Route::get('items/applyfilter', 'ItemController@applyfilter')->name('items.applyfilter');
Route::get('items/clearfilter', 'ItemController@clearfilter')->name('items.clearfilter');
Route::get('items/applysort', 'ItemController@applysort')->name('items.applysort');
Route::post('item/{item}/update', 'ItemController@update')->name('items.update');
Route::post('item/{item}/delete', 'ItemController@delete')->name('items.delete');
Route::get('items/bulkupload', 'ItemController@bulkupload')->name('items.bulkupload');
Route::get('items/downloadcsvtemplate', 'ItemController@downloadCsvTemplate')->name('items.downloadcsvtemplate');
Route::post('items/importcsv', 'ItemController@importcsv')->name('items.importcsv');
Route::post('items/massaction', 'ItemController@massaction')->name('items.massaction');

Route::get('employee/items/index', 'ItemController@employeeItemIndex')->name('items.employee.index');
Route::get('employee/items/create', 'ItemController@employeeItemCreate')->name('items.employee.create');
Route::post('employee/items/store', 'ItemController@employeeItemStore')->name('items.employee.store');
Route::post('employee/items/find', 'ItemController@employeeItemFind')->name('items.employee.find');
Route::get('employee/sales/entry', 'ItemController@employeeSalesEntry')->name('sales.employee.entry');
Route::get('employee/sales/form/{itemId}', 'ItemController@employeeSalesForm')->name('sales.employee.form');
Route::post('employee/sales/form/save', 'ItemController@employeeSalesFormSave')->name('sales.employee.form.save');

// Dashboard
Route::resource('dashboard', 'DashboardController')->only('index');

// Sales for Employee

Route::post('/profile/update', 'UserController@profileUpdate')->name('profile.update');

resources/views/items/employee/sales/entry.blade.php
@extends('layouts.admin')

@section('content')
<?php 
    $totalWeight = 0;
    $totalSales = 0;
?>
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">

            <div class="content-header">
                <div class="container-fluid">
                    <div class="row mb-2">
                        <div class="col-sm-6">
                            <h1 class="m-0 text-dark">{{ __("Sales") }}</h1>
                        </div><!-- /.col -->
                        <div class="col-sm-6">
                            <ol class="breadcrumb float-sm-right">
                                <li class="breadcrumb-item"><a href="/">{{ __("Home") }}</a></li>
                                <li class="breadcrumb-item active">{{ __("Sales") }}</li>
                            </ol>
                        </div><!-- /.col -->
                    </div><!-- /.row -->
                </div><!-- /.container-fluid -->
            </div>

            <div class="content">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-12">
                            <div class="float-right">
                                {{-- <a class="btn btn-primary mb-3" href="{{ route('items.create') }}" role="button"><span><i class="nav-icon fas fa-plus"></i></span></a>
                                <a class="btn btn-secondary mb-3" href="{{ route('items.bulkupload') }}" role="button">{{ __("Bulk Upload") }}</a> --}}
                            </div> 
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-12">
                            <div class="row">
                                <div class="col-12 mb-3">
                                    <div class="card">
                                        <div class="card-header">
                                            <div class="card-title">{{ __("Find Item") }}</div>
                                        </div>
                                        <div class="card-body">
                                            <form method="POST" action="{{ route('items.employee.find') }}">
                                                <div class="form-group row">
                                                    @csrf
                                                    <label for="item_no" class="col-3 col-form-label">Item No <span style="color: red">*</span></label>
                                                    <div class="col-6">
                                                        <input type="text" id="item_no" class="form-control" name="item_no" placeholder="Search Item No here.." value="{{ old('item_no') }}" required />
                                                    </div>
                                                    <div class="col-3">
                                                        <button type="submit" class="btn btn-primary">{{ __("Find") }}</button>
                                                    </div>
                                                </div>
                                            </form>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!-- /.row -->

                    <div class="row">
                        <div class="col-12">
                            <div class="card">
                                <div class="card-header">
                                    <div class="card-title">{{ __("Submitted Sales") }}</div>
                                </div>
                                <div class="card-body">
                                    <table
                                        class="table table-hover table-striped">
                                        <thead>
                                            <tr>
                                                <th>Date</th>
                                                <th>Item No</th>
                                                <th>Item Weight</th>
                                                <th>Sales Price</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            @foreach($today_list as $row)
                                            <tr>
                                                <td>{{ $row->sales_at }}</td>
                                                <td>{{ $row->item_no }}</td>
                                                <td>{{ StringHelper::formatDecimalDisplay($row->item_weight) }} gr</td>
                                                <td>Rp {{ StringHelper::formatDecimalDisplay($row->sales_price) }}</td>
                                            </tr>

                                            <?php 
                                                $totalWeight += $row->item_weight;
                                                $totalSales += $row->sales_price;
                                            ?>
                                            @endforeach
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-4">
                            <div class="card">
                                <div class="card-header">
                                    <div class="card-title">{{ __("Total Count Sold Item") }}</div>
                                </div>
                                <div class="card-body">
                                    <table
                                        class="table table-hover table-responsive table-striped text-nowrap">
                                        <thead>
                                            <tr>
                                                <th>Category Code</th>
                                                <th>Category Name</th>
                                                <th>Qty</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            @foreach($total_count_sold_items as $row)
                                            <tr>
                                                <td>{{ $row->category_code }}</td>
                                                <td>{{ $row->category_name }}</td>
                                                <td>{{ $row->item_count }}</td>
                                            </tr>
                                            @endforeach
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                        <div class="col-4">
                            <div class="card">
                                <div class="card-header">
                                    <div class="card-title">{{ __("Total Weight") }}</div>
                                </div>
                                <div class="card-body">
                                    <h1>{{ StringHelper::formatDecimalDisplay($totalWeight) }} gr</h1>
                                </div>
                            </div>
                        </div>
                        <div class="col-4">
                            <div class="card">
                                <div class="card-header">
                                    <div class="card-title">{{ __("Total Sales") }}</div>
                                </div>
                                <div class="card-body">
                                    <h1>Rp {{ StringHelper::formatDecimalDisplay($totalSales) }}</h1>
                                </div>
                            </div>
                        </div>
                    </div>
                
                </div><!-- /.container-fluid -->
            </div>

        </div>
    </div>
</div>
@endsection

{{-- @section('custom-script')
<script type="text/javascript">
    $('#card-detail').hide();

    function updateDetailForm() {
        // console.log($('#item_no').val());
        if($('#item_no').val() == '') {
            alert('Item No must be filled.');
            $('#card-detail').hide();
        } else {
            $('#card-detail').show();
        }
    }
</script>
@endsection --}}

resources/views/items/employee/sales/form.blade.php
@extends('layouts.admin')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">

			<div class="content-header">
				<div class="container-fluid">
					<div class="row mb-2">
						<div class="col-sm-6">
							<h1 class="m-0 text-dark">{{ __("Entry Sales") }}</h1>
						</div><!-- /.col -->
						<div class="col-sm-6">
							<ol class="breadcrumb float-sm-right">
								<li class="breadcrumb-item"><a href="/">{{ __("Home") }}</a></li>
								<li class="breadcrumb-item"><a href="{{ route("sales.employee.entry") }}">{{ __("Sales") }}</a></li>
								<li class="breadcrumb-item active">{{ __("Entry Sales") }}</li>
							</ol>
						</div><!-- /.col -->
					</div><!-- /.row -->
				</div><!-- /.container-fluid -->
			</div>

			<div class="content">
				<div class="container-fluid">
					<div class="row">
						<div class="col-12">
                            <div class="card">
                                <div class="card-header">
                                    <div class="card-title">{{ __("Sales Information") }}</div>
                                </div>
                                <div class="card-body">
                                    <form method="POST" action="{{ route('sales.employee.form.save') }}">
                                        @csrf
                                        <div class="form-group row" hidden>
                                            <label class="col-3 col-form-label">Item ID</label>
                                            <div class="col-9">
                                                <input type="text" class="form-control dateselect" id="item_id" name="item_id" value="{{ $item->id }}" />
                                            </div>
                                        </div>
                                        <div class="form-group row">
                                            <label class="col-3 col-form-label">Item No</label>
                                            <div class="col-9">
                                                {{ $item->item_no }}
                                            </div>
                                        </div>
                                        <div class="form-group row">
                                            <label class="col-3 col-form-label">Item Name</label>
                                            <div class="col-9">
                                                {{ $item->item_name }}
                                            </div>
                                        </div>
                                        <div class="form-group row">
                                            <label class="col-3 col-form-label">Item Weight</label>
                                            <div class="col-9">
                                                {{ $item->item_weight }} gr
                                            </div>
                                        </div>

                                        <div class="form-group row">
                                            <label for="sales_price" class="col-3 col-form-label">Sales Price</label>
                                            <div class="col-9">
                                                <div class="input-group">
                                                    <div class="input-group-prepend">
                                                            <div class="input-group-text">Rp</div>
                                                    </div>
                                                    <input type="text" class="form-control" name="sales_price" value="{{ old('sales_price') }}" />
                                                </div>
                                            </div>
                                        </div>
                                        <div class="form-group row">
                                            <label for="sales_at" class="col-3 col-form-label">Sales At</label>
                                            <div class="col-9">
                                                <div class="input-group">
                                                    <input type="text" class="form-control dateselect" id="sales_at" name="sales_at" placeholder="select date" value="{{ date('m/d/Y') }}" />
                                                </div>
                                            </div>
                                        </div>
                                        <div class="form-group row">
                                            <label for="sales_status_id" class="col-3 col-form-label">Sales Status</label>
                                            <div class="col-9">
                                                <input type="text" class="form-control" id="sales_status_id" name="sales_status_id" value="{{ $salesstatus->id }}" hidden />
                                                <input type="text" class="form-control" id="sales_status_text" name="sales_status_text" value="{{ $salesstatus->code }}" disabled />
                                            </div>
                                        </div>
                                        <div class="form-group row">
                                            <label for="sales_by" class="col-3 col-form-label">Sales By</label>
                                            <div class="col-9">
                                                <div class="input-group">
                                                    <input type="text" class="form-control dateselect" id="sales_by_id" name="sales_by_id" value="{{ Auth::user()->id }}" hidden />
                                                    <input type="text" class="form-control dateselect" id="sales_by_text" name="sales_by_text" value="{{ Auth::user()->name }}" disabled />
                                                </div>
                                            </div>
                                        </div>
                
                                        <div class="float-right">
                                            <a class="btn btn-secondary" href="{{ url()->previous() }}" role="button">{{ __("Back") }}</a>
                                            <button type="submit" class="btn btn-primary">{{ __("Save") }}</button>
                                        </div>
                                    </form>
                                </div>
                            </div>
						</div>
					</div>
					<!-- /.row -->
				</div><!-- /.container-fluid -->
			</div>

        </div>
    </div>
</div>
@endsection

@section('custom-script')
<script type="text/javascript">
	$(function() {
        $('#sales_at').datepicker();
    });
</script>
@endsection