routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
	if(Auth::check()) {
		return redirect('home');
	} else {
		return view('welcome');
	}
});

Auth::routes();

Route::get('/testemail', function() {
	$message = "Hello World!!!!";
    Mail::send('welcome', ['title' => 'Test Email', 'message' => $message], function($message) {
        $message->to('donny.p.perdana@gmail.com')->subject('Testing mails');
    });
});

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/profile', 'HomeController@profile')->name('profile');
// Route::get('/book', 'HomeController@book')->name('book');

// System Configuration > Stores
Route::resource('stores', 'StoreController')->only('index', 'create', 'store', 'edit');
Route::post('stores/{store}/update', 'StoreController@update')->name('stores.update');
Route::post('stores/{store}/delete', 'StoreController@delete')->name('stores.delete');

// System Configuration > Categories
Route::resource('categories', 'CategoryController')->only('index', 'create', 'store', 'edit');
Route::post('category/{category}/update', 'CategoryController@update')->name('categories.update');
Route::post('category/{category}/delete', 'CategoryController@delete')->name('categories.delete');

// System Configuration > Item Status
Route::resource('itemstatuses', 'ItemStatusController')->only('index', 'create', 'store', 'edit');
Route::post('itemstatus/{itemstatus}/update', 'ItemStatusController@update')->name('itemstatuses.update');
Route::post('itemstatus/{itemstatus}/delete', 'ItemStatusController@delete')->name('itemstatuses.delete');

// System Configuration > Inventory Status
Route::resource('inventorystatuses', 'InventoryStatusController')->only('index', 'create', 'store', 'edit');
Route::post('inventorystatus/{inventorystatus}/update', 'InventoryStatusController@update')->name('inventorystatuses.update');
Route::post('inventorystatus/{inventorystatus}/delete', 'InventoryStatusController@delete')->name('inventorystatuses.delete');

// System Configuration > Allocation
Route::resource('allocations', 'AllocationController')->only('index', 'create', 'store', 'edit');
Route::post('allocation/{allocation}/update', 'AllocationController@update')->name('allocations.update');
Route::post('allocation/{allocation}/delete', 'AllocationController@delete')->name('allocations.delete');

// System Configuration > Sales Status
Route::resource('salesstatuses', 'SalesStatusController')->only('index', 'create', 'store', 'edit');
Route::post('salesstatus/{salesstatus}/update', 'SalesStatusController@update')->name('salesstatuses.update');
Route::post('salesstatus/{salesstatus}/delete', 'SalesStatusController@delete')->name('salesstatuses.delete');

// System Configuration > Buyback Status
Route::resource('buybackstatuses', 'BuybackStatusController')->only('index', 'create', 'store', 'edit');
Route::post('buybackstatus/{buybackstatus}/update', 'BuybackStatusController@update')->name('buybackstatuses.update');
Route::post('buybackstatus/{buybackstatus}/delete', 'BuybackStatusController@delete')->name('buybackstatuses.delete');

// System Configuration > Users
Route::resource('users', 'UserController')->only('index', 'create', 'store', 'edit');
Route::get('users/{user}/changepassword', 'UserController@changepassword')->name('users.changepassword');
Route::post('users/{user}/update', 'UserController@update')->name('users.update');
Route::post('users/{user}/delete', 'UserController@delete')->name('users.delete');
Route::post('users/{user}/updatepassword', 'UserController@updatepassword')->name('users.updatepassword');

// System Configuration > Roles
Route::resource('roles', 'RoleController')->only('index', 'create', 'store', 'edit');
Route::post('roles/{role}/update', 'RoleController@update')->name('roles.update');
Route::post('roles/{role}/delete', 'RoleController@delete')->name('roles.delete');

// Book (Items)
Route::resource('items', 'ItemController')->only('index', 'create', 'store', 'edit');
Route::get('items/applyfilter', 'ItemController@applyfilter')->name('items.applyfilter');
Route::get('items/clearfilter', 'ItemController@clearfilter')->name('items.clearfilter');
Route::get('items/applysort', 'ItemController@applysort')->name('items.applysort');
Route::post('item/{item}/update', 'ItemController@update')->name('items.update');
Route::post('item/{item}/delete', 'ItemController@delete')->name('items.delete');
Route::get('items/bulkupload', 'ItemController@bulkupload')->name('items.bulkupload');
Route::get('items/downloadcsvtemplate', 'ItemController@downloadCsvTemplate')->name('items.downloadcsvtemplate');
Route::post('items/importcsv', 'ItemController@importcsv')->name('items.importcsv');
Route::post('items/massaction', 'ItemController@massaction')->name('items.massaction');

Route::get('employee/items/index', 'ItemController@employeeItemIndex')->name('items.employee.index');
Route::get('employee/items/create', 'ItemController@employeeItemCreate')->name('items.employee.create');
Route::post('employee/items/store', 'ItemController@employeeItemStore')->name('items.employee.store');
Route::post('employee/items/find', 'ItemController@employeeItemFind')->name('items.employee.find');
Route::get('employee/sales/entry', 'ItemController@employeeSalesEntry')->name('sales.employee.entry');
Route::get('employee/sales/form/{itemId}', 'ItemController@employeeSalesForm')->name('sales.employee.form');
Route::post('employee/sales/form/save', 'ItemController@employeeSalesFormSave')->name('sales.employee.form.save');

// Dashboard
Route::resource('dashboard', 'DashboardController')->only('index');

// Sales for Employee

Route::post('/profile/update', 'UserController@profileUpdate')->name('profile.update');

app/Allocation.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Allocation extends Model
{
    use SoftDeletes;

    protected $guarded = [];

    protected $table = 'allocation';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'code', 'description',
    ];

    public $sortable = [
        'code', 'description', 'created_at', 'updated_at',
    ];

    public static function search($query)
    {
        return empty($query) ? static::query()
            : static::where('code', 'like', '%'.$query.'%')
                ->orWhere('description', 'like', '%'.$query.'%');
    }
}

app/Http/Controllers/AllocationController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Allocation;

class AllocationController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct() {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('allocations.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('allocations.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'allocation_code' => 'required',
            'allocation_description' => 'required'
        ]);
        
        $allocation = new Allocation([
            'code' => $request->get('allocation_code'),
            'description' => $request->get('allocation_description'),
        ]);
        $allocation->save();

        return redirect('/allocations')->with('success', __('Allocation has been created.'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        try {
            $allocation = Allocation::findOrFail($id);
        } catch (Exception $ex) {
            return redirect()->route('allocations.index')->withError($ex->getMessage());
        }

        return view('allocations.edit')
            ->with('allocation', $allocation);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        try {
            $request->validate([
                'allocation_code' => 'required',
                'allocation_description' => 'required'
            ]);

            $allocation = Allocation::findOrFail($id);
            $allocation->code = $request->get("allocation_code");
            $allocation->description = $request->get("allocation_description");
            $allocation->save();

        } catch (Exception $ex) {
            return redirect('/allocations')->with('error', $ex->getMessage());
        }

        return redirect('/allocations')->with('success', __('Allocation has been updated.'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function delete($id)
    {
        try {
            $allocation = Allocation::findOrFail($id);
            $allocation->delete();
        } catch (Exception $ex) {
            return redirect('/allocations')->with('error', $ex->getMessage());
        }

        return redirect('/allocations')->with('success', __('Allocation has been deleted.'));
    }
}

app/Http/Livewire/AllocationsTable.php
<?php

namespace App\Http\Livewire;

use Livewire\Component;
use Livewire\WithPagination;

class AllocationsTable extends Component
{
	use WithPagination;	

    const INITIAL_SORT_FIELD = 'code';

    public $perPage = 10;
    public $sortField = self::INITIAL_SORT_FIELD;
    public $sortAsc = true;
    public $search = '';

    public function sortBy($field)
    {
        if ($this->sortField === $field) {
            $this->sortAsc = ! $this->sortAsc;
        } else {
            $this->sortAsc = true;
        }

        $this->sortField = $field;
    }

    public function render()
    {
        return view('livewire.allocations-table', [
            'allocations' => \App\Allocation::search($this->search)
                ->orderBy($this->sortField, $this->sortAsc ? 'asc' : 'desc')
                ->paginate($this->perPage),
        ]);
    }
}

resources/views/allocations/create.blade.php
@extends('layouts.admin')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">

			<div class="content-header">
				<div class="container-fluid">
					<div class="row mb-2">
						<div class="col-sm-6">
							<h1 class="m-0 text-dark">{{ __("New Allocation") }}</h1>
						</div><!-- /.col -->
						<div class="col-sm-6">
							<ol class="breadcrumb float-sm-right">
								<li class="breadcrumb-item"><a href="/">{{ __("Home") }}</a></li>
								<li class="breadcrumb-item"><a href="{{ route("allocations.index") }}">{{ __("Allocation") }}</a></li>
								<li class="breadcrumb-item active">{{ __("New Allocation") }}</li>
							</ol>
						</div><!-- /.col -->
					</div><!-- /.row -->
				</div><!-- /.container-fluid -->
			</div>

			<div class="content">
				<div class="container-fluid">
					<div class="row">
						<div class="col-12">
							<div class="table-responsive">
								<div class="card">
									<div class="card-body">
										<form method="POST" action="{{ route('allocations.store') }}">
											<div class="form-group">
												@csrf
												<label for="alz_code">Allocation Code</label>
												<input type="text" class="form-control" name="allocation_code" />
											</div>
											<div class="form-group">
												<label for="allocation_description">Allocation Description</label>
												<textarea class="form-control" name="allocation_description" rows="3"></textarea>
											</div>
			
											<div class="float-right">
												<a class="btn btn-secondary" href="{{ url()->previous() }}" role="button">{{ __("Back") }}</a>
												<button type="submit" class="btn btn-primary">{{ __("Save") }}</button>
											</div>
										</form>
									</div>
								</div>
							</div>
						</div>
					</div>
					<!-- /.row -->
				</div><!-- /.container-fluid -->
			</div>

        </div>
    </div>
</div>
@endsection

resources/views/allocations/edit.blade.php
@extends('layouts.admin')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">

            <div class="content-header">
                <div class="container-fluid">
                    <div class="row mb-2">
                        <div class="col-sm-6">
                            <h1 class="m-0 text-dark">{{ __("Edit Allocation") }}</h1>
                        </div><!-- /.col -->
                        <div class="col-sm-6">
                            <ol class="breadcrumb float-sm-right">
                                <li class="breadcrumb-item"><a href="/">{{ __("Home") }}</a></li>
                                <li class="breadcrumb-item"><a href="{{ route("allocations.index") }}">{{ __("Allocation") }}</a></li>
                                <li class="breadcrumb-item active">{{ __("Edit Allocation") }}</li>
                            </ol>
                        </div><!-- /.col -->
                    </div><!-- /.row -->
                </div><!-- /.container-fluid -->
            </div>

            <div class="content">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-12">
                            <div class="table-responsive">
                                <div class="card">
                                    <div class="card-body">
                                        <form method="post" action="{{ route('allocations.update', $allocation->id) }}">
                                            <div class="form-group">
                                                @csrf
                                                <label for="allocation_code">Allocation Code</label>
                                                <input type="text" class="form-control" name="allocation_code" value="{{ $allocation->code }}" />
                                            </div>
                                            <div class="form-group">
                                                <label for="allocation_description">Allocation Description</label>
                                                <textarea class="form-control" name="allocation_description" rows="3">{{ $allocation->description }}</textarea>
                                            </div>
            
                                            <div class="float-right">
                                                <a class="btn btn-secondary" href="{{ url()->previous() }}" role="button">{{ __("Back") }}</a>
                                                <button type="submit" class="btn btn-primary">{{ __("Save") }}</button>
                                            </div>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!-- /.row -->
                </div><!-- /.container-fluid -->
            </div>

        </div>
    </div>
</div>
@endsection

resources/views/allocations/index.blade.php
@extends('layouts.admin')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">

            <div class="content-header">
                <div class="container-fluid">
                    <div class="row mb-2">
                        <div class="col-sm-6">
                            <h1 class="m-0 text-dark">{{ __("Allocation") }}</h1>
                        </div><!-- /.col -->
                        <div class="col-sm-6">
                            <ol class="breadcrumb float-sm-right">
                                <li class="breadcrumb-item"><a href="/">{{ __("Home") }}</a></li>
                                <li class="breadcrumb-item active">{{ __("Allocation") }}</li>
                            </ol>
                        </div><!-- /.col -->
                    </div><!-- /.row -->
                </div><!-- /.container-fluid -->
            </div>

            <div class="content">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-12">
                                <a class="btn btn-primary float-right mb-3" href="{{ route('allocations.create') }}" role="button"><span><i class="nav-icon fas fa-plus"></i></span></a>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-12">
                            <div class="table-responsive">
                                <div class="card">
                                    <div class="card-body">
                                        @livewire('allocations-table')
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!-- /.row -->
                </div><!-- /.container-fluid -->
            </div>

        </div>
    </div>
</div>
@endsection